### ISSUE TITLE
iOS Sign In Issue

### ISSUE THREAD

**Issue by DWNorman47** [faizann/UnityGPGPlugin#1]
I get the game to open up the sign in screen, I hit accept for allowing it access to whatever, it sends me back into the game, but nothing changes. Clicking to sign in again brings up the same window that requires accepting. Your troubleshooting does mention a sign in problem that may be the same (it's very vague), but I can't figure out how to fix it from what was written. This is for iOS deployment, done from a Mac, if that makes a difference.

**Comment by faizann** [comment]
Hi
Did you get issue resolved? I think it was related to not having openURL working in AppController.mm

**Comment by DWNorman47** [comment]
Yes, I did figure out this issue and it was the URL thing. Thank you.

**Comment by anushree9** [comment]
Can you specify exactly how you solved the issue? I am having the exact same issue.
Thanks in advance!

**Comment by DWNorman47** [comment]
Sorry, it's been too long and I ended up going with a different plugin due to other problems. I don't remember what I did, and I can't seem to find it right now. I think this project has changed since I last messed with it.
