### ISSUE TITLE
how can i get gmail public profile on login 

### ISSUE THREAD

**Issue by wasim-bashir-incubasys** [faizann/UnityGPGPlugin#14]
i want use gmail login for my game and i want user public profile for my own server.
means 
first name ,last name ,male , email etc

**Comment by wasimjj** [comment]
i want the same thing how can we use gamil apis for public profile

**Comment by faizann** [comment]
By gmail I guess you mean google+ account. I don't think UnityGPGPlugin supports the information you want but you can easily add it to plugin yourself. We are not developing on UnityGPGPlugin anymore.

**Comment by wasimjj** [comment]
okay thank you..
login failed due to google services there is any  thing wrong with old or new library. could you send me older 
compatible res(google services )
