### ISSUE TITLE
4.4 Google Play Services

### ISSUE THREAD

**Issue by mimminito** [faizann/UnityGPGPlugin#4]
This does not work with the latest Google Play Services. Could you please ensure its working with the latest Android OS 4.4. I have tested on a Nexus 4 and Nexus 10 and both crash when trying to use this.

**Comment by faizann** [comment]
Hi

My Nexus 7 still hasn't received Android 4.4. I will test as soon I get it.
In the mean time lets fix it with your logs/trace. Can you send a log/trace of where it crashes.

**Comment by mimminito** [comment]
Sure, here is the stacktrace from LogCat:

11-26 14:08:00.621: E/AndroidRuntime(6321): Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=9002, result=0, data=null} to activity {package.name.removed/com.nerdiacs.nerdgpgplugin.NerdUnityPlayerActivity}: java.lang.NullPointerException
11-26 14:08:00.621: E/AndroidRuntime(6321):     at android.app.ActivityThread.deliverResults(ActivityThread.java:3346)
11-26 14:08:00.621: E/AndroidRuntime(6321):     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3389)
11-26 14:08:00.621: E/AndroidRuntime(6321):     at android.app.ActivityThread.access$1200(ActivityThread.java:135)
11-26 14:08:00.621: E/AndroidRuntime(6321):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1445)
11-26 14:08:00.621: E/AndroidRuntime(6321):     at android.os.Handler.dispatchMessage(Handler.java:102)
11-26 14:08:00.621: E/AndroidRuntime(6321):     at android.os.Looper.loop(Looper.java:137)
11-26 14:08:00.621: E/AndroidRuntime(6321):     at android.app.ActivityThread.main(ActivityThread.java:4998)
11-26 14:08:00.621: E/AndroidRuntime(6321):     at java.lang.reflect.Method.invokeNative(Native Method)
11-26 14:08:00.621: E/AndroidRuntime(6321):     at java.lang.reflect.Method.invoke(Method.java:515)
11-26 14:08:00.621: E/AndroidRuntime(6321):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
11-26 14:08:00.621: E/AndroidRuntime(6321):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
11-26 14:08:00.621: E/AndroidRuntime(6321):     at dalvik.system.NativeStart.main(Native Method)
11-26 14:08:00.621: E/AndroidRuntime(6321): Caused by: java.lang.NullPointerException
11-26 14:08:00.621: E/AndroidRuntime(6321):     at com.nerdiacs.nerdgpgplugin.NerdUnityPlayerActivity.onActivityResult(NerdUnityPlayerActivity.java:30)
11-26 14:08:00.621: E/AndroidRuntime(6321):     at android.app.Activity.dispatchActivityResult(Activity.java:5435)
11-26 14:08:00.621: E/AndroidRuntime(6321):     at android.app.ActivityThread.deliverResults(ActivityThread.java:3342)
11-26 14:08:00.621: E/AndroidRuntime(6321):     ... 11 more

**Comment by faizann** [comment]
Most probably your manifest file doesn't have NerdUnityPlayerActivity as main activity. Do check manifest or paste here for me to check.

This is needed for Facebook compatibility of this plugin. So, a bit bad way of doing it but only way.

**Comment by mimminito** [comment]
Hi, 

This appears to be setup correctly, I have used your Editor Plugin and that reported a success. Here is the manifest
http://pastebin.com/WZWuTbXb

**Comment by faizann** [comment]
Now I am out of suggestions. Manifest looks good but the activity object is not available at runtime.
Is the sample code working for you GPGUI.cs
You said it doesn't work on android 4.4. does it work fine for you on older android?

**Comment by mimminito** [comment]
I will try and test this on another device soon. I will also try and test
the sample in a fresh project and check if it works.

On Tue, Nov 26, 2013 at 3:54 PM, Faizan Naqvi notifications@github.comwrote:

> Now I am out of suggestions. Manifest looks good but the activity object
> is not available at runtime.
> Is the sample code working for you GPGUI.cs
> You said it doesn't work on android 4.4. does it work fine for you on
> older android?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/faizann/UnityGPGPlugin/issues/4#issuecomment-29303711
> .

## 

Adam Goodchild

**Comment by faizann** [comment]
I changed a bit of code. Replace GPGPlugin.jar with this one http://nerdiacs.com/downloads/GPGPlugin.jar so that it is included in your project and app on installation.

**Comment by mimminito** [comment]
Ok thanks, ill test this later and let you know.

**Comment by mimminito** [comment]
This has fixed the issue! Thank you very much for sorting this so quick, I am on a time critical development cycle and this has helped a great deal!

**Comment by tahir90** [comment]
Iam also having the same exception please provide the jar file again as the above .jar link is not working.thanks!

**Comment by faizann** [comment]
Hi Tahir

Link is back up now. You can download from here http://nerdiacs.com/downloads/GPGPlugin.jar

**Comment by tahir90** [comment]
thanks for the link!
